checksumBehavior: update

enableColors: true

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.devnet?
  - .env.local?

nodeLinker: node-modules

npmScopes:
  coinweb:
    npmPublishRegistry: "https://npm.coinweb.io/"
    npmRegistryServer: "https://npm.coinweb.io/"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
